from django.conf.urls import patterns, include, url
from django.contrib import admin
from stone import views
import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$',views.homepage),
    url(r'^About/$',views.About),
    url(r'^hjm/$',views.hjm),
    url(r'^hxs/$',views.hjm),
    url(r'^yx/$',views.hjm),
    url(r'^hzxm/$',views.hjm),
    url(r'^bm/$',views.hjm),
    url(r'^lys/$',views.hjm),
    url(r'^hl/$',views.hjm),
    url(r'^gc/$',views.hjm),
    url(r'^gcal/$',views.gcal),
    url(r'^feedback/$',views.feedback),
    url(r'^service/$',views.service),
    url(r'^delete/(\d+)/$',views.delete),
    url(r'^top/$',views.top),
    url(r'^bottom/$',views.bottom),
    url(r'^left_contect/$',views.left_contect),
    url(r'^left_contect1/$',views.left_contect1),
    url(r'^left_contect0/$',views.left_contect0),
    url(r'^gcal/picture1/$',views.picture1),
    url(r'^gcal/picture2/$',views.picture2),
    url(r'^gcal/picture3/$',views.picture3),
    url(r'^gcal/picture4/$',views.picture4),
    url(r'^gcal/picture5/$',views.picture5),
    url(r'^gcal/picture6/$',views.picture6),
    url(r'^list/$',views.list),
    url(r'^list_5/$',views.list),
    url(r'^list_4/$',views.list),
    url(r'^list_3/$',views.list),
    url(r'^list_2/$',views.list),
    url(r'^list_1/$',views.list),
    url(r'^picture/$',views.picture),
    url(r'^culture/$',views.culture),
    url(r'^news/$',views.news),
    url(r'^product/$',views.product),
    url(r'^hiring/$',views.hiring),
    url(r'^contect/$',views.contect),
    url(r'^gcal_Index_1/$',views.gcal_Index_1),
    url(r'^gcal_Index_2/$',views.gcal_Index_2),
    url(r'^gcal_Index_3/$',views.gcal_Index_3),
    url(r'^list_cpzs/$',views.list_cpzs),

    url( r'^static/(?P<path>.*)$', 'django.views.static.serve',{ 'document_root': settings.STATIC_URL }),
)
